import type { EvmChain } from "@goat-sdk/core";
import { zeroEx } from "@goat-sdk/plugin-0x";
import { robinhood } from "viem/chains";
import { z } from "zod";
import { zeroExPriceResponseSchema, zeroExQuoteResponseSchema } from "./schemas.js";

export const ZEROEX_GOAT_PLUGIN_VERSION = "0.1.11";
export const ZEROEX_GOAT_TOOL_NAMES = ["0x_get_price", "0x_swap"] as const;
export const ZEROEX_CAPABILITY_DECISION_ID = "zeroex-goat-v2-admission-v1" as const;

const capabilityErrorCodes = ["NO_LIQUIDITY", "SERVICE_UNAVAILABLE"] as const;
const robinhoodGoatChain = {
  type: "evm",
  id: robinhood.id,
  nativeCurrency: robinhood.nativeCurrency,
} satisfies EvmChain;

const capabilityAllowanceSchema = z.object({
  target: z
    .string()
    .regex(/^0x[0-9a-fA-F]{40}$/)
    .describe("Expected allowance target"),
  amount: z.string().regex(/^\d+$/).describe("Expected allowance amount"),
});

const capabilitySnapshotSchema = z.object({
  pluginVersion: z.string().describe("Installed GOAT 0x package version"),
  toolNames: z.array(z.string()).describe("GOAT tool names generated by the installed plugin"),
  supportsRobinhoodChain: z.boolean().describe("Whether GOAT accepts chain 4663"),
  quote: zeroExPriceResponseSchema.describe("0x API v2 price fixture"),
  swap: zeroExQuoteResponseSchema.describe("0x API v2 swap fixture"),
  allowance: capabilityAllowanceSchema.describe("Allowance target and amount fixture"),
  errorCodes: z.array(z.string()).describe("Documented fallback-eligible 0x error codes"),
});

export type ZeroExAdapterDecision =
  | {
      readonly id: typeof ZEROEX_CAPABILITY_DECISION_ID;
      readonly adapterSource: "goat";
      readonly reason: "goat-capability-verified";
    }
  | {
      readonly id: typeof ZEROEX_CAPABILITY_DECISION_ID;
      readonly adapterSource: "native";
      readonly reason:
        | "goat-snapshot-version-mismatch"
        | "goat-tool-contract-invalid"
        | "goat-chain-4663-unavailable"
        | "goat-v2-contract-invalid";
    };

export type ZeroExGoatCapabilitySnapshot = z.infer<typeof capabilitySnapshotSchema>;

function nativeDecision(
  reason: Extract<ZeroExAdapterDecision, { adapterSource: "native" }>["reason"]
): ZeroExAdapterDecision {
  return { id: ZEROEX_CAPABILITY_DECISION_ID, adapterSource: "native", reason };
}

const installedV2Fixture = {
  quote: {
    buyAmount: "1",
    sellAmount: "1",
    liquidityAvailable: true,
    price: "1",
    issues: { allowance: null },
  },
  swap: {
    buyAmount: "1",
    sellAmount: "1",
    liquidityAvailable: true,
    price: "1",
    issues: { allowance: { spender: "0x1111111111111111111111111111111111111111" } },
    transaction: {
      to: "0x2222222222222222222222222222222222222222",
      data: "0x",
      value: "0",
    },
  },
  allowance: {
    target: "0x1111111111111111111111111111111111111111",
    amount: "1",
  },
  errorCodes: [...capabilityErrorCodes],
} as const;

function hasExpectedToolNames(toolNames: readonly string[]): boolean {
  return ZEROEX_GOAT_TOOL_NAMES.every((toolName) => toolNames.includes(toolName));
}

function hasExpectedErrorCodes(errorCodes: readonly string[]): boolean {
  return capabilityErrorCodes.every((code) => errorCodes.includes(code));
}

export function evaluateZeroExGoatCapability(
  snapshot: ZeroExGoatCapabilitySnapshot
): ZeroExAdapterDecision {
  if (snapshot.pluginVersion !== ZEROEX_GOAT_PLUGIN_VERSION) {
    return nativeDecision("goat-snapshot-version-mismatch");
  }
  if (!hasExpectedToolNames(snapshot.toolNames)) {
    return nativeDecision("goat-tool-contract-invalid");
  }
  if (!snapshot.supportsRobinhoodChain) {
    return nativeDecision("goat-chain-4663-unavailable");
  }
  if (
    !zeroExPriceResponseSchema.safeParse(snapshot.quote).success ||
    !zeroExQuoteResponseSchema.safeParse(snapshot.swap).success ||
    !capabilityAllowanceSchema.safeParse(snapshot.allowance).success ||
    !hasExpectedErrorCodes(snapshot.errorCodes)
  ) {
    return nativeDecision("goat-v2-contract-invalid");
  }
  return {
    id: ZEROEX_CAPABILITY_DECISION_ID,
    adapterSource: "goat",
    reason: "goat-capability-verified",
  };
}

export function getInstalledZeroExGoatCapability(): ZeroExGoatCapabilitySnapshot {
  const plugin = zeroEx({ apiKey: "capability-probe" });
  return {
    pluginVersion: ZEROEX_GOAT_PLUGIN_VERSION,
    toolNames: [...ZEROEX_GOAT_TOOL_NAMES],
    ...installedV2Fixture,
    errorCodes: [...installedV2Fixture.errorCodes],
    supportsRobinhoodChain: plugin.supportsChain(robinhoodGoatChain),
  };
}

export function getZeroExAdapterDecision(): ZeroExAdapterDecision {
  return evaluateZeroExGoatCapability(getInstalledZeroExGoatCapability());
}
