import { zodToJsonSchema } from "zod-to-json-schema";
import type { ToolCategory } from "../../runtime/types.js";
import type { ToolDefinition } from "../../tools/register.js";
import {
  evmApproveTokenSpending,
  evmGetAllowance,
  evmGetBalance,
  evmGetBlock,
  evmGetChainInfo,
  evmGetContractAbi,
  evmGetErc1155Balance,
  evmGetGasPrice,
  evmGetLatestBlock,
  evmGetNftInfo,
  evmGetSupportedNetworks,
  evmGetTokenBalance,
  evmGetTransaction,
  evmGetTransactionReceipt,
  evmGetWalletAddress,
  evmListRegisteredAbis,
  evmLookupEnsAddress,
  evmMulticall,
  evmReadContract,
  evmRegisterAbi,
  evmResolveEnsName,
  evmSignMessage,
  evmSignTypedData,
  evmTransferErc20,
  evmTransferNative,
  evmWaitForTransaction,
  evmWriteContract,
} from "./handlers.js";
import {
  evmApproveTokenSchema,
  evmGetAllowanceSchema,
  evmGetBalanceSchema,
  evmGetBlockSchema,
  evmGetChainInfoSchema,
  evmGetContractAbiSchema,
  evmGetErc1155BalanceSchema,
  evmGetGasPriceSchema,
  evmGetLatestBlockSchema,
  evmGetNftInfoSchema,
  evmGetTokenBalanceSchema,
  evmGetTransactionReceiptSchema,
  evmGetTransactionSchema,
  evmListRegisteredAbisSchema,
  evmLookupEnsSchema,
  evmMulticallSchema,
  evmReadContractSchema,
  evmRegisterAbiSchema,
  evmResolveEnsSchema,
  evmSignMessageSchema,
  evmSignTypedDataSchema,
  evmTransferErc20Schema,
  evmTransferNativeSchema,
  evmWaitForTransactionSchema,
  evmWriteContractSchema,
} from "./schemas.js";

const CATEGORY: ToolCategory = "onchain";

export function getEvmToolDefinitions(): ToolDefinition[] {
  return [
    {
      name: "evm_get_wallet_address",
      category: CATEGORY,
      description: "Get the currently active wallet address, mode, and chain context.",
      inputSchema: {
        type: "object" as const,
        properties: {},
        required: [],
      },
      handler: evmGetWalletAddress,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_chain_info",
      category: CATEGORY,
      description: "Get basic chain status including latest block number for a chain ID.",
      inputSchema: zodToJsonSchema(evmGetChainInfoSchema) as Record<string, unknown>,
      handler: evmGetChainInfo,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_supported_networks",
      category: CATEGORY,
      description: "List supported EVM networks available for EVM tool operations.",
      inputSchema: {
        type: "object" as const,
        properties: {},
        required: [],
      },
      handler: evmGetSupportedNetworks,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_gas_price",
      category: CATEGORY,
      description: "Get current base gas price and priority fee estimates for a chain.",
      inputSchema: zodToJsonSchema(evmGetGasPriceSchema) as Record<string, unknown>,
      handler: evmGetGasPrice,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_resolve_ens_name",
      category: CATEGORY,
      description: "Resolve an ENS name to an EVM address.",
      inputSchema: zodToJsonSchema(evmResolveEnsSchema) as Record<string, unknown>,
      handler: evmResolveEnsName,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_lookup_ens_address",
      category: CATEGORY,
      description: "Perform reverse ENS lookup for an address.",
      inputSchema: zodToJsonSchema(evmLookupEnsSchema) as Record<string, unknown>,
      handler: evmLookupEnsAddress,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_block",
      category: CATEGORY,
      description: "Get block details by block number string or block hash.",
      inputSchema: zodToJsonSchema(evmGetBlockSchema) as Record<string, unknown>,
      handler: evmGetBlock,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_latest_block",
      category: CATEGORY,
      description: "Get the latest block details for a chain.",
      inputSchema: zodToJsonSchema(evmGetLatestBlockSchema) as Record<string, unknown>,
      handler: evmGetLatestBlock,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_transaction",
      category: CATEGORY,
      description: "Get transaction details for a transaction hash.",
      inputSchema: zodToJsonSchema(evmGetTransactionSchema) as Record<string, unknown>,
      handler: evmGetTransaction,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_transaction_receipt",
      category: CATEGORY,
      description: "Get the transaction receipt (status, logs, gas usage) for a hash.",
      inputSchema: zodToJsonSchema(evmGetTransactionReceiptSchema) as Record<string, unknown>,
      handler: evmGetTransactionReceipt,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_wait_for_transaction",
      category: CATEGORY,
      description: "Wait for transaction confirmations and return the confirmed receipt.",
      inputSchema: zodToJsonSchema(evmWaitForTransactionSchema) as Record<string, unknown>,
      handler: evmWaitForTransaction,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_balance",
      category: CATEGORY,
      description:
        "Get NATIVE token balance (ETH, MATIC, BNB, etc.) for an address or ENS name. This does NOT return ERC-20 token balances — use evm_get_token_balance for that.",
      inputSchema: zodToJsonSchema(evmGetBalanceSchema) as Record<string, unknown>,
      handler: evmGetBalance,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_token_balance",
      category: CATEGORY,
      description:
        "Get ERC-20 token balance (USDC, WETH, DAI, etc.) for an owner address. Requires the token contract address. For native token balance (ETH, MATIC), use evm_get_balance instead.",
      inputSchema: zodToJsonSchema(evmGetTokenBalanceSchema) as Record<string, unknown>,
      handler: evmGetTokenBalance,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_allowance",
      category: CATEGORY,
      description: "Get ERC-20 allowance from owner to spender for a token contract.",
      inputSchema: zodToJsonSchema(evmGetAllowanceSchema) as Record<string, unknown>,
      handler: evmGetAllowance,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_contract_abi",
      category: CATEGORY,
      description: "Fetch a contract ABI from Etherscan for a specific chain.",
      inputSchema: zodToJsonSchema(evmGetContractAbiSchema) as Record<string, unknown>,
      handler: evmGetContractAbi,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_register_abi",
      category: CATEGORY,
      description:
        "Register a contract ABI under a label for reuse. Once registered, pass abiLabel to evm_read_contract, evm_write_contract, or evm_multicall instead of repeating the full ABI JSON on every call.",
      inputSchema: zodToJsonSchema(evmRegisterAbiSchema) as Record<string, unknown>,
      handler: evmRegisterAbi,
      annotations: { readOnlyHint: true, openWorldHint: false },
    },
    {
      name: "evm_list_registered_abis",
      category: CATEGORY,
      description: "List all ABI labels registered via evm_register_abi.",
      inputSchema: zodToJsonSchema(evmListRegisteredAbisSchema) as Record<string, unknown>,
      handler: evmListRegisteredAbis,
      annotations: { readOnlyHint: true, openWorldHint: false },
    },
    {
      name: "evm_read_contract",
      category: CATEGORY,
      description:
        "Read contract state by function name. Provide abiLabel (from evm_register_abi), abiJson, or let the tool auto-resolve from Etherscan.",
      inputSchema: zodToJsonSchema(evmReadContractSchema) as Record<string, unknown>,
      handler: evmReadContract,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_nft_info",
      category: CATEGORY,
      description: "Get ERC-721 NFT details including collection metadata, owner, and tokenURI.",
      inputSchema: zodToJsonSchema(evmGetNftInfoSchema) as Record<string, unknown>,
      handler: evmGetNftInfo,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_get_erc1155_balance",
      category: CATEGORY,
      description: "Get ERC-1155 token balance for an owner and token ID.",
      inputSchema: zodToJsonSchema(evmGetErc1155BalanceSchema) as Record<string, unknown>,
      handler: evmGetErc1155Balance,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_multicall",
      category: CATEGORY,
      description: "Batch multiple contract read calls into one multicall RPC request.",
      inputSchema: zodToJsonSchema(evmMulticallSchema) as Record<string, unknown>,
      handler: evmMulticall,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    {
      name: "evm_write_contract",
      category: CATEGORY,
      description:
        "Execute a state-changing contract function. Provide abiLabel (from evm_register_abi), abiJson, or let the tool auto-resolve. Confirmation-gated.",
      inputSchema: zodToJsonSchema(evmWriteContractSchema) as Record<string, unknown>,
      handler: evmWriteContract,
      riskLevel: "financial",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
    {
      name: "evm_transfer_native",
      category: CATEGORY,
      description: "Send native tokens (ETH, MATIC, etc.) to an address or ENS name.",
      inputSchema: zodToJsonSchema(evmTransferNativeSchema) as Record<string, unknown>,
      handler: evmTransferNative,
      riskLevel: "financial",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
    {
      name: "evm_transfer_erc20",
      category: CATEGORY,
      description:
        "Transfer ERC-20 tokens. Amount is in the token's smallest unit (e.g. for USDC with 6 decimals, '1000000' = 1 USDC). Use evm_get_token_balance to check decimals first.",
      inputSchema: zodToJsonSchema(evmTransferErc20Schema) as Record<string, unknown>,
      handler: evmTransferErc20,
      riskLevel: "financial",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
    {
      name: "evm_approve_token_spending",
      category: CATEGORY,
      description: "Approve ERC-20 spender allowance using raw token units.",
      inputSchema: zodToJsonSchema(evmApproveTokenSchema) as Record<string, unknown>,
      handler: evmApproveTokenSpending,
      riskLevel: "financial",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
    {
      name: "evm_sign_message",
      category: CATEGORY,
      description: "Sign an arbitrary UTF-8 message with the active wallet.",
      inputSchema: zodToJsonSchema(evmSignMessageSchema) as Record<string, unknown>,
      handler: evmSignMessage,
      riskLevel: "destructive",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
    {
      name: "evm_sign_typed_data",
      category: CATEGORY,
      description: "Sign EIP-712 typed data payload with the active wallet.",
      inputSchema: zodToJsonSchema(evmSignTypedDataSchema) as Record<string, unknown>,
      handler: evmSignTypedData,
      riskLevel: "destructive",
      annotations: { destructiveHint: true, openWorldHint: true },
    },
  ];
}
