export const NATIVE_ALIASES: Readonly<Record<number, Readonly<Record<string, string>>>> = {
  1: { ETH: "WETH" },
  10: { ETH: "WETH" },
  56: { BNB: "WBNB" },
  100: { XDAI: "WXDAI" },
  137: { MATIC: "WMATIC", POL: "WMATIC" },
  324: { ETH: "WETH" },
  4663: { ETH: "WETH" },
  5000: { MNT: "WMNT" },
  8453: { ETH: "WETH" },
  34443: { ETH: "WETH" },
  42161: { ETH: "WETH" },
  43114: { AVAX: "WAVAX" },
  59144: { ETH: "WETH" },
  81457: { ETH: "WETH" },
  534352: { ETH: "WETH" },
};

export const DEXSCREENER_CHAIN_SLUGS: Readonly<Record<number, string>> = {
  1: "ethereum",
  10: "optimism",
  56: "bsc",
  100: "gnosis",
  137: "polygon",
  324: "zksync",
  4663: "robinhood",
  5000: "mantle",
  8453: "base",
  34443: "mode",
  42161: "arbitrum",
  42220: "celo",
  43114: "avalanche",
  59144: "linea",
  81457: "blast",
  534352: "scroll",
};

export const REPUTATION_EQUIVALENTS: Readonly<Record<string, readonly string[]>> = {
  ETH: ["ETH", "WETH"],
  WETH: ["WETH", "ETH"],
  BTC: ["BTC", "WBTC"],
  WBTC: ["WBTC", "BTC"],
  BNB: ["BNB", "WBNB"],
  WBNB: ["WBNB", "BNB"],
  MATIC: ["MATIC", "WMATIC", "POL", "WPOL"],
  WMATIC: ["WMATIC", "MATIC", "POL", "WPOL"],
  POL: ["POL", "WPOL", "WMATIC", "MATIC"],
  WPOL: ["WPOL", "POL", "WMATIC", "MATIC"],
  AVAX: ["AVAX", "WAVAX"],
  WAVAX: ["WAVAX", "AVAX"],
  MNT: ["MNT", "WMNT"],
  WMNT: ["WMNT", "MNT"],
  XDAI: ["XDAI", "WXDAI", "DAI"],
  WXDAI: ["WXDAI", "XDAI", "DAI"],
  USDC: ["USDC", "USDC.E"],
  "USDC.E": ["USDC.E", "USDC"],
};
